# Generated by Django 5.2.3 on 2025-06-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipping',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
