# Generated by Django 5.2.3 on 2025-07-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag_clipping_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipping',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
